### PR TITLE
[innogy] Update README.md

### PR DESCRIPTION
**Pull request by nik70000**
[innogy] Added BT-PSS (Bluetooth Pluggable Smart Switch) and editorial changes

### CODE REVIEW

**Comment by Hilbrand** [comment]
@nik70000 Can you add a Sign-off either to the pr or to a commit:
`Signed-off-by: [full name] <email address>`

**Comment by nik70000** [comment]
Hi Hilbrand,

 

as you see, I am new to the openHAB development world, so apologies for my mistakes. For the moment, I have closed my pull request as there is no stable code base to work from yet. Once there is a working version for innogy API 1.1 and OH2.5, I can then try again to introduce new device support (which I then will sign-off as well)

 

Thank you for your hints (and your support to the innogy binding),

Nicholas

**Comment by Hilbrand** [comment]
No problem. If you just put the signoff text here I'll merge your changes here in my branch so these changes will not be lost.

**Comment by nik70000** [comment]
„here“ means: by email? I am using the web interface of GitHUB and have not found any ways to do the signoff from there…

Signed-off-by: Nicholas Prinz github@prinzenweb.de

**Comment by Hilbrand** [comment]
It's indeed not possible to edit commits on GitHub web interface. It's possible to edit the pull request text. I've merged your pr and fixed the typo in it.

**Pull request merged**
